# Rockchip RK3399 hexa core 4GB SoC GBe eMMC USB3 WiFi/BT
BOARD_NAME="Hisense hs530r"
BOARDFAMILY="rockchip64"
BOOTCONFIG="rock-pi-4-rk3399_defconfig"
KERNEL_TARGET="current,edge"
FULL_DESKTOP="yes"
BOOT_LOGO="desktop"
BOOT_FDT_FILE="rockchip/rk3399-hs530r.dtb"
#DDR_BLOB="rk33/rk3399_ddr_800MHz_v1.27.bin"
#xxx#BOOT_SCENARIO="blobless"
#xxx#BOOT_SCENARIO="only-blobs"
#xxx#BOOT_SCENARIO="tpl-spl-blob"
#x#BOOT_SCENARIO="spl-blobs"
BOOT_SCENARIO="tpl-blob-atf-mainline"
